// packages/react/src/pages/PortalWalletsPage.tsx
import React from 'react'
import type { PortalWallet } from '@monigo/portal-core'
import { useMonigoContext } from '../provider/context'
import { WalletList } from '../components/WalletList'

export interface PortalWalletsPageProps {
  onWalletClick?: (w: PortalWallet) => void
  className?: string
}

export function PortalWalletsPage({ onWalletClick, className = '' }: PortalWalletsPageProps): React.ReactElement {
  const { messages } = useMonigoContext()
  return (
    <section className={`monigo-page ${className}`}>
      <h1 style={{ fontSize: 'var(--monigo-text-2xl)', marginBottom: 'var(--monigo-space-5)' }}>{messages['wallets.title']}</h1>
      <WalletList {...(onWalletClick !== undefined && { onWalletClick })} />
    </section>
  )
}

// packages/svelte/src/pages/PortalWalletsPage.svelte
<script lang="ts">
  import WalletList from '../components/WalletList.svelte'
  import { getMonigoContext } from '../provider/context'
  import type { PortalWallet } from '@monigo/portal-core'

  interface Props {
    onWalletClick?: (w: PortalWallet) => void
    class?: string
  }
  const { onWalletClick, class: className = '' }: Props = $props()
  const { messages } = getMonigoContext()
</script>

<section class="page {className}">
  <h1>{messages['wallets.title']}</h1>
  {#if onWalletClick}
    <WalletList {onWalletClick} />
  {:else}
    <WalletList />
  {/if}
</section>

<style>
  h1 { font-size: var(--monigo-text-2xl); margin-bottom: var(--monigo-space-5); }
</style>
