// packages/vue/src/components/BillList.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { formatCurrency, formatDate, type Bill } from '@monigo/portal-core'
import { useMonigoContext } from '../provider/context'
import { useBills } from '../stores/useBills'
import BillStatusBadge from './BillStatusBadge.vue'
import Skeleton from './shared/Skeleton.vue'
import EmptyState from './shared/EmptyState.vue'
import ErrorState from './shared/ErrorState.vue'

interface Props {
  limit?: number
  page?: number
  class?: string
}
const props = withDefaults(defineProps<Props>(), { limit: 20, page: 1, class: '' })
const emit = defineEmits<{ billClick: [bill: Bill] }>()

const { client, messages, locale } = useMonigoContext()
const { state, dispatch, dispose } = useBills(client)

onMounted(() => dispatch({ type: 'load', page: props.page, limit: props.limit }))
onUnmounted(dispose)

const tableStyle = {
  width: '100%',
  borderCollapse: 'collapse' as const,
}
const cellStyle = {
  padding: 'var(--monigo-space-3)',
  textAlign: 'left' as const,
  fontSize: 'var(--monigo-text-sm)',
  borderBottom: '1px solid var(--monigo-color-border)',
}
const thStyle = { ...cellStyle, color: 'var(--monigo-color-muted-fg)', fontWeight: '500' }
</script>

<template>
  <div :class="['monigo-bill-list', props.class]">
    <Skeleton v-if="state.status === 'idle' || state.status === 'loading'" :rows="5" />
    <ErrorState
      v-else-if="state.status === 'error'"
      :error="state.error"
      :on-retry="() => dispatch({ type: 'refresh' })"
      :retry-label="messages['common.retry']"
    />
    <EmptyState v-else-if="state.bills.length === 0" :message="messages['bills.empty']" />
    <table v-else :style="tableStyle">
      <thead>
        <tr>
          <th :style="thStyle">Payout #</th>
          <th :style="thStyle">Date</th>
          <th :style="thStyle">Amount</th>
          <th :style="thStyle">Status</th>
        </tr>
      </thead>
      <tbody>
        <tr
          v-for="bill in state.bills"
          :key="bill.id"
          :style="{ cursor: 'pointer' }"
          class="monigo-row"
          tabindex="0"
          role="button"
          @click="emit('billClick', bill)"
          @keydown.enter="emit('billClick', bill)"
        >
          <td :style="cellStyle">{{ bill.number }}</td>
          <td :style="cellStyle">{{ formatDate(bill.issued_at, locale) }}</td>
          <td :style="cellStyle">{{ formatCurrency(bill.total, bill.currency, locale) }}</td>
          <td :style="cellStyle"><BillStatusBadge :status="bill.status" /></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<style scoped>
.monigo-row:hover { background: var(--monigo-color-muted); }
.monigo-row:focus-visible { outline: 2px solid var(--monigo-color-primary); outline-offset: -2px; }
</style>

// packages/svelte/src/components/BillList.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { getMonigoContext } from '../provider/context'
  import { createBillsRune } from '../stores/bills.svelte'
  import { formatCurrency, formatDate, type Bill } from '@monigo/portal-core'
  import BillStatusBadge from './BillStatusBadge.svelte'
  import Skeleton from './shared/Skeleton.svelte'
  import EmptyState from './shared/EmptyState.svelte'
  import ErrorState from './shared/ErrorState.svelte'

  interface Props {
    limit?: number
    page?: number
    onBillClick?: (bill: Bill) => void
    class?: string
  }

  const { limit = 20, page = 1, onBillClick, class: className = '' }: Props = $props()

  const { client, messages, locale } = getMonigoContext()
  const rune = createBillsRune(client)

  onMount(() => { rune.dispatch({ type: 'load', page, limit }) })
  onDestroy(() => { rune.dispose() })
</script>

<div class="bill-list {className}">
  {#if rune.state.status === 'idle' || rune.state.status === 'loading'}
    <Skeleton rows={5} />
  {:else if rune.state.status === 'error'}
    <ErrorState error={rune.state.error} onRetry={() => rune.dispatch({ type: 'refresh' })} retryLabel={messages['common.retry']} />
  {:else if rune.state.bills.length === 0}
    <EmptyState message={messages['bills.empty']} />
  {:else}
    <table>
      <thead>
        <tr>
          <th>Bill #</th>
          <th>Date</th>
          <th>Amount</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        {#each rune.state.bills as bill (bill.id)}
          <tr class="row" onclick={() => onBillClick?.(bill)} onkeydown={(e) => e.key === 'Enter' && onBillClick?.(bill)} tabindex={onBillClick ? 0 : -1} role={onBillClick ? 'button' : undefined}>
            <td>{bill.number}</td>
            <td>{formatDate(bill.issued_at, locale)}</td>
            <td>{formatCurrency(bill.total, bill.currency, locale)}</td>
            <td><BillStatusBadge status={bill.status} /></td>
          </tr>
        {/each}
      </tbody>
    </table>
  {/if}
</div>

<style>
  table { width: 100%; border-collapse: collapse; }
  th, td { padding: var(--monigo-space-3); text-align: left; font-size: var(--monigo-text-sm); border-bottom: 1px solid var(--monigo-color-border); }
  th { color: var(--monigo-color-muted-fg); font-weight: 500; }
  .row { cursor: pointer; }
  .row:hover { background: var(--monigo-color-muted); }
  .row:focus-visible { outline: 2px solid var(--monigo-color-primary); outline-offset: -2px; }
</style>
