// packages/vue/src/components/FundWalletButton.vue
<script setup lang="ts">
import { ref } from 'vue'
import { useMonigoContext } from '../provider/context'

interface Props {
  walletId: string
  currency: string
  label?: string
  class?: string
}
const props = withDefaults(defineProps<Props>(), { class: '' })
const emit = defineEmits<{
  success: [result: { authorization_url: string }]
  error: [err: unknown]
}>()

const { client, messages } = useMonigoContext()
const showInput = ref(false)
const amount = ref('')
const loading = ref(false)

const handleFund = async () => {
  if (!amount.value || loading.value) return
  loading.value = true
  try {
    const result = await client.fundWallet(props.walletId, {
      amount: amount.value,
      currency: props.currency,
    })
    emit('success', result)
    if (typeof window !== 'undefined') {
      window.location.href = result.authorization_url
    }
  } catch (err) {
    emit('error', err)
  } finally {
    loading.value = false
    showInput.value = false
    amount.value = ''
  }
}
</script>

<template>
  <div :class="['monigo-fund-wallet-btn', props.class]">
    <button
      v-if="!showInput"
      type="button"
      :style="{
        padding: 'var(--monigo-space-2) var(--monigo-space-4)',
        background: 'var(--monigo-color-primary)',
        color: 'var(--monigo-color-primary-fg)',
        border: 'none',
        borderRadius: 'var(--monigo-radius-md)',
        fontSize: 'var(--monigo-text-sm)',
        cursor: 'pointer',
      }"
      @click="showInput = true"
    >
      {{ props.label ?? messages['wallets.action.fund'] }}
    </button>
    <div
      v-else
      :style="{ display: 'flex', gap: 'var(--monigo-space-2)', alignItems: 'center' }"
    >
      <input
        v-model="amount"
        type="number"
        min="0"
        :placeholder="`Amount (${props.currency})`"
        :style="{
          padding: 'var(--monigo-space-2)',
          border: '1px solid var(--monigo-color-border)',
          borderRadius: 'var(--monigo-radius-sm)',
          fontSize: 'var(--monigo-text-sm)',
          width: '140px',
        }"
      />
      <button
        type="button"
        :disabled="loading || !amount"
        :style="{
          padding: 'var(--monigo-space-2) var(--monigo-space-3)',
          background: 'var(--monigo-color-primary)',
          color: 'var(--monigo-color-primary-fg)',
          border: 'none',
          borderRadius: 'var(--monigo-radius-sm)',
          fontSize: 'var(--monigo-text-sm)',
          cursor: loading ? 'not-allowed' : 'pointer',
          opacity: loading ? '0.6' : '1',
        }"
        @click="handleFund"
      >
        {{ loading ? messages['common.loading'] : messages['common.confirm'] }}
      </button>
      <button
        type="button"
        :style="{
          padding: 'var(--monigo-space-2) var(--monigo-space-3)',
          background: 'transparent',
          color: 'var(--monigo-color-muted-fg)',
          border: '1px solid var(--monigo-color-border)',
          borderRadius: 'var(--monigo-radius-sm)',
          fontSize: 'var(--monigo-text-sm)',
          cursor: 'pointer',
        }"
        @click="showInput = false; amount = ''"
      >
        {{ messages['common.cancel'] }}
      </button>
    </div>
  </div>
</template>

// packages/svelte/src/components/FundWalletButton.svelte
<script lang="ts">
  import { getMonigoContext } from '../provider/context'

  interface Props {
    walletId: string
    currency: string
    class?: string
    onError?: (err: unknown) => void
  }
  const { walletId, currency, class: className = '', onError }: Props = $props()
  const { client, messages } = getMonigoContext()

  let amount = $state('')
  let loading = $state(false)
  let open = $state(false)

  async function fund() {
    if (!amount || parseFloat(amount) <= 0) return
    loading = true
    try {
      const result = await client.fundWallet(walletId, { amount, currency })
      if (typeof window !== 'undefined') window.location.href = result.authorization_url
    } catch (err) {
      onError?.(err)
    } finally {
      loading = false
    }
  }
</script>

<div class="fund-wallet {className}">
  {#if !open}
    <button type="button" class="toggle" onclick={() => (open = true)}>{messages['wallets.action.fund']}</button>
  {:else}
    <form onsubmit={(e) => { e.preventDefault(); fund() }}>
      <label>
        <span class="sr-only">Amount</span>
        <input type="number" step="0.01" min="0" bind:value={amount} placeholder={`Amount (${currency})`} required disabled={loading} />
      </label>
      <button type="submit" disabled={loading || !amount}>{loading ? messages['common.loading'] : messages['wallets.action.fund']}</button>
      <button type="button" class="cancel" onclick={() => { open = false; amount = '' }} disabled={loading}>{messages['common.cancel']}</button>
    </form>
  {/if}
</div>

<style>
  .toggle, button[type='submit'] {
    padding: var(--monigo-space-2) var(--monigo-space-4);
    background: var(--monigo-color-primary);
    color: var(--monigo-color-primary-fg);
    border: none;
    border-radius: var(--monigo-radius-md);
    font-size: var(--monigo-text-sm);
    cursor: pointer;
  }
  button[type='submit']:disabled { opacity: 0.5; cursor: not-allowed; }
  form { display: flex; gap: var(--monigo-space-2); align-items: center; }
  input { padding: var(--monigo-space-2); border: 1px solid var(--monigo-color-border); border-radius: var(--monigo-radius-sm); font-size: var(--monigo-text-sm); }
  .cancel { background: transparent; color: var(--monigo-color-muted-fg); border: 1px solid var(--monigo-color-border); padding: var(--monigo-space-2) var(--monigo-space-3); border-radius: var(--monigo-radius-md); cursor: pointer; }
  .sr-only { position: absolute; width: 1px; height: 1px; padding: 0; margin: -1px; overflow: hidden; clip: rect(0,0,0,0); white-space: nowrap; border: 0; }
</style>
