// packages/vue/src/components/InvoiceStatusBadge.vue
<script setup lang="ts">
import { computed } from 'vue'
import { formatInvoiceStatus } from '@monigo/portal-core'

interface Props {
  status: string
  class?: string
}
const props = withDefaults(defineProps<Props>(), { class: '' })

type Variant = 'success' | 'danger' | 'warning' | 'muted'

const variant = computed<Variant>(() =>
  props.status === 'paid' ? 'success' :
  props.status === 'payment_failed' ? 'danger' :
  props.status === 'finalized' ? 'warning' :
  'muted'
)

const variantStyles: Record<Variant, Record<string, string>> = {
  success: {
    background: 'color-mix(in srgb, var(--monigo-color-success) 15%, transparent)',
    color: 'var(--monigo-color-success)',
  },
  danger: {
    background: 'color-mix(in srgb, var(--monigo-color-danger) 15%, transparent)',
    color: 'var(--monigo-color-danger)',
  },
  warning: {
    background: 'color-mix(in srgb, var(--monigo-color-warning) 15%, transparent)',
    color: 'var(--monigo-color-warning)',
  },
  muted: {
    background: 'var(--monigo-color-muted)',
    color: 'var(--monigo-color-muted-fg)',
  },
}

const badgeStyle = computed(() => ({
  display: 'inline-block',
  padding: '2px var(--monigo-space-2)',
  borderRadius: 'var(--monigo-radius-sm)',
  fontSize: 'var(--monigo-text-xs)',
  fontWeight: '500',
  lineHeight: '1.4',
  ...variantStyles[variant.value],
}))
</script>

<template>
  <span :class="['monigo-badge', props.class]" :style="badgeStyle">
    {{ formatInvoiceStatus(props.status) }}
  </span>
</template>

// packages/svelte/src/components/InvoiceStatusBadge.svelte
<script lang="ts">
  import { formatInvoiceStatus } from '@monigo/portal-core'

  interface Props {
    status: string
    class?: string
  }
  const { status, class: className = '' }: Props = $props()

  const variant = $derived(
    status === 'paid' ? 'success' :
    status === 'payment_failed' ? 'danger' :
    status === 'finalized' ? 'warning' :
    'muted'
  )
</script>

<span class="badge badge-{variant} {className}">{formatInvoiceStatus(status)}</span>

<style>
  .badge {
    display: inline-block;
    padding: 2px var(--monigo-space-2);
    border-radius: var(--monigo-radius-sm);
    font-size: var(--monigo-text-xs);
    font-weight: 500;
    line-height: 1.4;
  }
  .badge-success { background: color-mix(in srgb, var(--monigo-color-success) 15%, transparent); color: var(--monigo-color-success); }
  .badge-danger { background: color-mix(in srgb, var(--monigo-color-danger) 15%, transparent); color: var(--monigo-color-danger); }
  .badge-warning { background: color-mix(in srgb, var(--monigo-color-warning) 15%, transparent); color: var(--monigo-color-warning); }
  .badge-muted { background: var(--monigo-color-muted); color: var(--monigo-color-muted-fg); }
</style>
