// packages/vue/src/components/PayoutAccountCard.vue
<script setup lang="ts">
import type { CustomerPayoutAccount } from '@monigo/portal-core'

interface Props {
  account: CustomerPayoutAccount
  class?: string
}
const props = withDefaults(defineProps<Props>(), { class: '' })

const maskedAccount = (account: CustomerPayoutAccount): string => {
  const num = account.account_number ?? account.mobile_money_number
  if (!num) return '—'
  return `••••${num.slice(-4)}`
}
</script>

<template>
  <div
    :class="['monigo-payout-account-card', props.class]"
    :style="{
      padding: 'var(--monigo-space-4)',
      border: '1px solid var(--monigo-color-border)',
      borderRadius: 'var(--monigo-radius-md)',
    }"
  >
    <div :style="{ display: 'flex', justifyContent: 'space-between', marginBottom: 'var(--monigo-space-2)' }">
      <span :style="{ fontWeight: '500', fontSize: 'var(--monigo-text-sm)' }">
        {{ props.account.bank_name ?? props.account.payout_method }}
      </span>
      <span :style="{ fontSize: 'var(--monigo-text-xs)', color: 'var(--monigo-color-muted-fg)' }">
        {{ props.account.currency }}
      </span>
    </div>
    <p :style="{ margin: '0', fontSize: 'var(--monigo-text-sm)', color: 'var(--monigo-color-muted-fg)' }">
      {{ maskedAccount(props.account) }}
      <span v-if="props.account.account_name"> — {{ props.account.account_name }}</span>
    </p>
    <span
      v-if="props.account.is_default"
      :style="{
        display: 'inline-block',
        marginTop: 'var(--monigo-space-2)',
        padding: '2px var(--monigo-space-2)',
        background: 'color-mix(in srgb, var(--monigo-color-success) 15%, transparent)',
        color: 'var(--monigo-color-success)',
        borderRadius: 'var(--monigo-radius-sm)',
        fontSize: 'var(--monigo-text-xs)',
        fontWeight: '500',
      }"
    >
      Default
    </span>
  </div>
</template>

// packages/svelte/src/components/PayoutAccountCard.svelte
<script lang="ts">
  import type { CustomerPayoutAccount } from '@monigo/portal-core'

  interface Props {
    account: CustomerPayoutAccount
    class?: string
  }
  const { account, class: className = '' }: Props = $props()

  const methodLabel = $derived(
    account.payout_method === 'bank_transfer' ? 'Bank transfer' :
    account.payout_method === 'mobile_money' ? 'Mobile money' :
    account.payout_method,
  )

  const maskedAccount = $derived(
    account.account_number
      ? `\u2022\u2022\u2022\u2022 ${account.account_number.slice(-4)}`
      : null,
  )

  const maskedMobile = $derived(
    account.mobile_money_number
      ? `\u2022\u2022\u2022\u2022 ${account.mobile_money_number.slice(-4)}`
      : null,
  )
</script>

<article class="pa-card {className}">
  <header class="head">
    <div class="info">
      <h3 class="name">{account.account_name}</h3>
      {#if account.is_default}
        <span class="badge-default">Default</span>
      {/if}
    </div>
    <span class="currency">{account.currency}</span>
  </header>

  <p class="method">{methodLabel}</p>

  {#if account.payout_method === 'bank_transfer'}
    {#if account.bank_name}
      <p class="detail">
        {account.bank_name}{maskedAccount ? ` \u00b7 ${maskedAccount}` : ''}
      </p>
    {:else if maskedAccount}
      <p class="detail">{maskedAccount}</p>
    {/if}
  {:else if maskedMobile}
    <p class="detail">{maskedMobile}</p>
  {/if}
</article>

<style>
  .pa-card {
    padding: var(--monigo-space-5);
    border: 1px solid var(--monigo-color-border);
    border-radius: var(--monigo-radius-lg);
    background: var(--monigo-color-bg);
    margin-bottom: var(--monigo-space-3);
  }
  .head {
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    margin-bottom: var(--monigo-space-2);
  }
  .info { display: flex; align-items: center; gap: var(--monigo-space-2); flex-wrap: wrap; }
  .name { margin: 0; font-size: var(--monigo-text-lg); font-weight: 600; }
  .badge-default {
    font-size: var(--monigo-text-xs);
    font-weight: 500;
    padding: 0.1em var(--monigo-space-2);
    border-radius: 9999px;
    background: color-mix(in srgb, var(--monigo-color-primary) 12%, transparent);
    color: var(--monigo-color-primary);
  }
  .currency {
    font-size: var(--monigo-text-xs);
    font-weight: 600;
    padding: 0.15em var(--monigo-space-2);
    border-radius: var(--monigo-radius-md);
    background: color-mix(in srgb, var(--monigo-color-muted-fg) 12%, transparent);
    color: var(--monigo-color-muted-fg);
    white-space: nowrap;
  }
  .method {
    margin: 0 0 var(--monigo-space-1);
    font-size: var(--monigo-text-sm);
    color: var(--monigo-color-muted-fg);
  }
  .detail {
    margin: 0;
    font-size: var(--monigo-text-sm);
    color: var(--monigo-color-muted-fg);
  }
</style>
