// packages/react/src/components/WalletList.tsx
import React, { useEffect } from 'react'
import { type PortalWallet } from '@monigo/portal-core'
import { useMonigoContext } from '../provider/context'
import { useWallets } from '../hooks/useWallets'
import { WalletCard } from './WalletCard'
import { Skeleton } from './shared/Skeleton'
import { EmptyState } from './shared/EmptyState'
import { ErrorState } from './shared/ErrorState'

export interface WalletListProps {
  onWalletClick?: (wallet: PortalWallet) => void
  className?: string
}

export function WalletList({ onWalletClick, className = '' }: WalletListProps): React.ReactElement {
  const { client, messages } = useMonigoContext()
  const { state, dispatch } = useWallets(client)

  useEffect(() => { dispatch({ type: 'load' }) }, [dispatch])

  if (state.status === 'idle' || state.status === 'loading') return <Skeleton rows={3} />
  if (state.status === 'error') {
    return <ErrorState error={state.error} onRetry={() => dispatch({ type: 'refresh' })} retryLabel={messages['common.retry']} />
  }
  if (state.wallets.length === 0) return <EmptyState message={messages['wallets.empty']} />

  return (
    <div className={`monigo-wallet-list ${className}`} style={{ display: 'flex', flexDirection: 'column', gap: 'var(--monigo-space-3)' }}>
      {state.wallets.map((wallet) => (
        <WalletCard key={wallet.id} wallet={wallet} {...(onWalletClick !== undefined && { onClick: onWalletClick })} />
      ))}
    </div>
  )
}

// packages/svelte/src/components/WalletList.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { getMonigoContext } from '../provider/context'
  import { createWalletsRune } from '../stores/wallets.svelte'
  import type { PortalWallet } from '@monigo/portal-core'
  import WalletCard from './WalletCard.svelte'
  import Skeleton from './shared/Skeleton.svelte'
  import EmptyState from './shared/EmptyState.svelte'
  import ErrorState from './shared/ErrorState.svelte'

  interface Props {
    onWalletClick?: (wallet: PortalWallet) => void
    class?: string
  }
  const { onWalletClick, class: className = '' }: Props = $props()

  const { client, messages } = getMonigoContext()
  const rune = createWalletsRune(client)

  onMount(() => { rune.dispatch({ type: 'load' }) })
  onDestroy(() => { rune.dispose() })
</script>

<div class="wallet-list {className}">
  {#if rune.state.status === 'idle' || rune.state.status === 'loading'}
    <Skeleton rows={3} />
  {:else if rune.state.status === 'error'}
    <ErrorState error={rune.state.error} onRetry={() => rune.dispatch({ type: 'refresh' })} retryLabel={messages['common.retry']} />
  {:else if rune.state.wallets.length === 0}
    <EmptyState message={messages['wallets.empty']} />
  {:else}
    {#each rune.state.wallets as wallet (wallet.id)}
      {#if onWalletClick}
        <WalletCard {wallet} onClick={onWalletClick} />
      {:else}
        <WalletCard {wallet} />
      {/if}
    {/each}
  {/if}
</div>
