// packages/react/src/pages/PortalPayoutAccountsPage.tsx
import React from 'react'
import { useMonigoContext } from '../provider/context'
import { PayoutAccountList } from '../components/PayoutAccountList'

export interface PortalPayoutAccountsPageProps {
  className?: string
}

export function PortalPayoutAccountsPage({ className = '' }: PortalPayoutAccountsPageProps): React.ReactElement {
  const { messages } = useMonigoContext()
  return (
    <section className={`monigo-page ${className}`}>
      <h1 style={{ fontSize: 'var(--monigo-text-2xl)', marginBottom: 'var(--monigo-space-5)' }}>{messages['payout_accounts.title']}</h1>
      <PayoutAccountList />
    </section>
  )
}

// packages/vue/src/pages/PortalPayoutAccountsPage.vue
<script setup lang="ts">
import { useMonigoContext } from '../provider/context'
import PayoutAccountList from '../components/PayoutAccountList.vue'

interface Props { class?: string }
const props = withDefaults(defineProps<Props>(), { class: '' })

const { messages } = useMonigoContext()
</script>

<template>
  <section :class="['monigo-page', props.class]">
    <h1 :style="{ fontSize: 'var(--monigo-text-2xl)', marginBottom: 'var(--monigo-space-5)' }">{{ messages['payout_accounts.title'] }}</h1>
    <PayoutAccountList />
  </section>
</template>
