// packages/svelte/src/pages/PortalSubscriptionsPage.svelte
<script lang="ts">
  import SubscriptionList from '../components/SubscriptionList.svelte'
  import { getMonigoContext } from '../provider/context'
  import type { PortalSubscription } from '@monigo/portal-core'

  interface Props {
    oncancel?: (sub: PortalSubscription) => void
    class?: string
  }
  const { oncancel, class: className = '' }: Props = $props()
  const { messages } = getMonigoContext()
</script>

<section class="page {className}">
  <h1>{messages['subscriptions.title']}</h1>
  {#if oncancel}
    <SubscriptionList {oncancel} />
  {:else}
    <SubscriptionList />
  {/if}
</section>

<style>
  h1 { font-size: var(--monigo-text-2xl); margin-bottom: var(--monigo-space-5); }
</style>

// packages/vue/src/pages/PortalSubscriptionsPage.vue
<script setup lang="ts">
import { useMonigoContext } from '../provider/context'
import SubscriptionList from '../components/SubscriptionList.vue'

interface Props { class?: string }
const props = withDefaults(defineProps<Props>(), { class: '' })

const { messages } = useMonigoContext()
</script>

<template>
  <section :class="['monigo-page', props.class]">
    <h1 :style="{ fontSize: 'var(--monigo-text-2xl)', marginBottom: 'var(--monigo-space-5)' }">{{ messages['subscriptions.title'] }}</h1>
    <SubscriptionList />
  </section>
</template>
