// packages/react/src/pages/PortalInvoiceDetailPage.tsx
import React from 'react'
import { InvoiceDetail } from '../components/InvoiceDetail'

export interface PortalInvoiceDetailPageProps {
  invoiceId: string
  className?: string
}

export function PortalInvoiceDetailPage({ invoiceId, className = '' }: PortalInvoiceDetailPageProps): React.ReactElement {
  return <InvoiceDetail invoiceId={invoiceId} className={className} />
}

// packages/vue/src/pages/PortalInvoiceDetailPage.vue
<script setup lang="ts">
import InvoiceDetail from '../components/InvoiceDetail.vue'

interface Props {
  invoiceId: string
  class?: string
}
const props = withDefaults(defineProps<Props>(), { class: '' })
</script>

<template>
  <InvoiceDetail :invoice-id="props.invoiceId" :class="props.class" />
</template>
