// packages/react/src/pages/PortalInvoicesPage.tsx
import React from 'react'
import type { PortalInvoice } from '@monigo/portal-core'
import { useMonigoContext } from '../provider/context'
import { InvoiceList } from '../components/InvoiceList'

export interface PortalInvoicesPageProps {
  onInvoiceClick?: (i: PortalInvoice) => void
  className?: string
}

export function PortalInvoicesPage({ onInvoiceClick, className = '' }: PortalInvoicesPageProps): React.ReactElement {
  const { messages } = useMonigoContext()
  return (
    <section className={`monigo-page ${className}`}>
      <h1 style={{ fontSize: 'var(--monigo-text-2xl)', marginBottom: 'var(--monigo-space-5)' }}>{messages['invoices.title']}</h1>
      <InvoiceList {...(onInvoiceClick !== undefined && { onInvoiceClick })} />
    </section>
  )
}

// packages/vue/src/pages/PortalInvoicesPage.vue
<script setup lang="ts">
import type { PortalInvoice } from '@monigo/portal-core'
import { useMonigoContext } from '../provider/context'
import InvoiceList from '../components/InvoiceList.vue'

interface Props { class?: string }
const props = withDefaults(defineProps<Props>(), { class: '' })
const emit = defineEmits<{ invoiceClick: [inv: PortalInvoice] }>()

const { messages } = useMonigoContext()
</script>

<template>
  <section :class="['monigo-page', props.class]">
    <h1 :style="{ fontSize: 'var(--monigo-text-2xl)', marginBottom: 'var(--monigo-space-5)' }">{{ messages['invoices.title'] }}</h1>
    <InvoiceList @invoice-click="(inv) => emit('invoiceClick', inv)" />
  </section>
</template>
