// packages/vue/src/pages/PortalWalletDetailPage.vue
<script setup lang="ts">
import WalletDetail from '../components/WalletDetail.vue'
import WalletTransactionList from '../components/WalletTransactionList.vue'

interface Props {
  walletId: string
  class?: string
}
const props = withDefaults(defineProps<Props>(), { class: '' })
</script>

<template>
  <section :class="['monigo-page', props.class]">
    <WalletDetail :wallet-id="props.walletId" />
    <WalletTransactionList :wallet-id="props.walletId" :style="{ marginTop: 'var(--monigo-space-5)' }" />
  </section>
</template>

// packages/react/src/pages/PortalWalletDetailPage.tsx
import React from 'react'
import { WalletDetail } from '../components/WalletDetail'
import { WalletTransactionList } from '../components/WalletTransactionList'

export interface PortalWalletDetailPageProps {
  walletId: string
  className?: string
}

export function PortalWalletDetailPage({ walletId, className = '' }: PortalWalletDetailPageProps): React.ReactElement {
  return (
    <section className={`monigo-page ${className}`}>
      <WalletDetail walletId={walletId} />
      <WalletTransactionList walletId={walletId} />
    </section>
  )
}
