// packages/vue/src/pages/PortalDashboardPage.vue
<script setup lang="ts">
import type { PortalInvoice, Bill } from '@monigo/portal-core'
import DashboardSummary from '../components/DashboardSummary.vue'
import RecentActivity from '../components/RecentActivity.vue'

interface Props { class?: string }
const props = withDefaults(defineProps<Props>(), { class: '' })
const emit = defineEmits<{
  invoiceClick: [inv: PortalInvoice]
  billClick: [bill: Bill]
}>()
</script>

<template>
  <section :class="['monigo-page', props.class]">
    <DashboardSummary />
    <RecentActivity
      @invoice-click="(inv) => emit('invoiceClick', inv)"
      @bill-click="(bill) => emit('billClick', bill)"
    />
  </section>
</template>

// packages/react/src/pages/PortalDashboardPage.tsx
import React from 'react'
import type { PortalInvoice, Bill } from '@monigo/portal-core'
import { DashboardSummary } from '../components/DashboardSummary'
import { RecentActivity } from '../components/RecentActivity'

export interface PortalDashboardPageProps {
  onInvoiceClick?: (i: PortalInvoice) => void
  onBillClick?: (b: Bill) => void
  className?: string
}

export function PortalDashboardPage({ onInvoiceClick, onBillClick, className = '' }: PortalDashboardPageProps): React.ReactElement {
  return (
    <section className={`monigo-page ${className}`}>
      <DashboardSummary />
      <RecentActivity onInvoiceClick={onInvoiceClick} onBillClick={onBillClick} />
    </section>
  )
}
