// packages/vue/src/components/PaymentMethodList.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { useMonigoContext } from '../provider/context'
import { usePaymentMethods } from '../stores/usePaymentMethods'
import PaymentMethodCard from './PaymentMethodCard.vue'
import RemovePaymentMethodButton from './RemovePaymentMethodButton.vue'
import SetDefaultPaymentMethodButton from './SetDefaultPaymentMethodButton.vue'
import Skeleton from './shared/Skeleton.vue'
import EmptyState from './shared/EmptyState.vue'
import ErrorState from './shared/ErrorState.vue'

interface Props { class?: string }
const props = withDefaults(defineProps<Props>(), { class: '' })

const { client, messages } = useMonigoContext()
const { state, dispatch, dispose } = usePaymentMethods(client)

onMounted(() => dispatch({ type: 'load' }))
onUnmounted(dispose)

const refresh = () => dispatch({ type: 'refresh' })
</script>

<template>
  <div :class="['monigo-pm-list', props.class]">
    <Skeleton v-if="state.status === 'idle' || state.status === 'loading'" :rows="3" />
    <ErrorState
      v-else-if="state.status === 'error'"
      :error="state.error"
      :on-retry="() => dispatch({ type: 'refresh' })"
      :retry-label="messages['common.retry']"
    />
    <EmptyState v-else-if="state.paymentMethods.length === 0" :message="messages['payment_methods.empty']" />
    <div
      v-else
      :style="{ display: 'flex', flexDirection: 'column', gap: 'var(--monigo-space-3)' }"
    >
      <div
        v-for="method in state.paymentMethods"
        :key="method.id"
        :style="{ display: 'flex', alignItems: 'center', gap: 'var(--monigo-space-2)' }"
      >
        <PaymentMethodCard :method="method" :style="{ flex: '1' }" />
        <div :style="{ display: 'flex', gap: 'var(--monigo-space-2)' }">
          <SetDefaultPaymentMethodButton
            v-if="!method.is_default"
            :payment-method-id="method.id"
            @set="refresh"
          />
          <RemovePaymentMethodButton
            :payment-method-id="method.id"
            @remove="refresh"
          />
        </div>
      </div>
    </div>
  </div>
</template>

// packages/react/src/components/PaymentMethodList.tsx
import React, { useEffect } from 'react'
import { useMonigoContext } from '../provider/context'
import { usePaymentMethods } from '../hooks/usePaymentMethods'
import { PaymentMethodCard } from './PaymentMethodCard'
import { RemovePaymentMethodButton } from './RemovePaymentMethodButton'
import { SetDefaultPaymentMethodButton } from './SetDefaultPaymentMethodButton'
import { Skeleton } from './shared/Skeleton'
import { EmptyState } from './shared/EmptyState'
import { ErrorState } from './shared/ErrorState'

export interface PaymentMethodListProps {
  className?: string
}

export function PaymentMethodList({ className = '' }: PaymentMethodListProps): React.ReactElement {
  const { client, messages } = useMonigoContext()
  const { state, dispatch } = usePaymentMethods(client)

  useEffect(() => { dispatch({ type: 'load' }) }, [dispatch])

  if (state.status === 'idle' || state.status === 'loading') return <Skeleton rows={3} />
  if (state.status === 'error') {
    return <ErrorState error={state.error} onRetry={() => dispatch({ type: 'refresh' })} retryLabel={messages['common.retry']} />
  }
  if (state.paymentMethods.length === 0) return <EmptyState message={messages['payment_methods.empty']} />

  return (
    <div className={`monigo-pm-list ${className}`} style={{ display: 'flex', flexDirection: 'column', gap: 'var(--monigo-space-2)' }}>
      {state.paymentMethods.map((method) => (
        <div key={method.id} style={{ display: 'flex', flexDirection: 'column', gap: 'var(--monigo-space-1)' }}>
          <PaymentMethodCard method={method} />
          <div style={{ display: 'flex', gap: 'var(--monigo-space-2)', paddingLeft: 'var(--monigo-space-1)' }}>
            {!method.is_default && (
              <SetDefaultPaymentMethodButton
                paymentMethodId={method.id}
                onSet={() => dispatch({ type: 'refresh' })}
              />
            )}
            <RemovePaymentMethodButton
              paymentMethodId={method.id}
              onRemove={() => dispatch({ type: 'refresh' })}
            />
          </div>
        </div>
      ))}
    </div>
  )
}
