// packages/vue/src/components/SubscriptionList.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import { useMonigoContext } from '../provider/context'
import { useSubscriptions } from '../stores/useSubscriptions'
import SubscriptionCard from './SubscriptionCard.vue'
import Skeleton from './shared/Skeleton.vue'
import EmptyState from './shared/EmptyState.vue'
import ErrorState from './shared/ErrorState.vue'

interface Props { class?: string }
const props = withDefaults(defineProps<Props>(), { class: '' })

const { client, messages } = useMonigoContext()
const { state, dispatch, dispose } = useSubscriptions(client)

onMounted(() => dispatch({ type: 'load' }))
onUnmounted(dispose)
</script>

<template>
  <div :class="['monigo-sub-list', props.class]">
    <Skeleton v-if="state.status === 'idle' || state.status === 'loading'" :rows="3" />
    <ErrorState
      v-else-if="state.status === 'error'"
      :error="state.error"
      :on-retry="() => dispatch({ type: 'refresh' })"
      :retry-label="messages['common.retry']"
    />
    <EmptyState v-else-if="state.subscriptions.length === 0" :message="messages['subscriptions.empty']" />
    <div
      v-else
      :style="{ display: 'flex', flexDirection: 'column', gap: 'var(--monigo-space-3)' }"
    >
      <SubscriptionCard
        v-for="sub in state.subscriptions"
        :key="sub.id"
        :subscription="sub"
      />
    </div>
  </div>
</template>

// packages/react/src/components/SubscriptionList.tsx
import React, { useEffect } from 'react'
import { useMonigoContext } from '../provider/context'
import { useSubscriptions } from '../hooks/useSubscriptions'
import { SubscriptionCard } from './SubscriptionCard'
import { Skeleton } from './shared/Skeleton'
import { EmptyState } from './shared/EmptyState'
import { ErrorState } from './shared/ErrorState'

export interface SubscriptionListProps {
  className?: string
}

export function SubscriptionList({ className = '' }: SubscriptionListProps): React.ReactElement {
  const { client, messages } = useMonigoContext()
  const { state, dispatch } = useSubscriptions(client)

  useEffect(() => { dispatch({ type: 'load' }) }, [dispatch])

  if (state.status === 'idle' || state.status === 'loading') return <Skeleton rows={3} />
  if (state.status === 'error') {
    return <ErrorState error={state.error} onRetry={() => dispatch({ type: 'refresh' })} retryLabel={messages['common.retry']} />
  }
  if (state.subscriptions.length === 0) return <EmptyState message={messages['subscriptions.empty']} />

  return (
    <div className={`monigo-sub-list ${className}`} style={{ display: 'flex', flexDirection: 'column', gap: 'var(--monigo-space-3)' }}>
      {state.subscriptions.map((sub) => (
        <SubscriptionCard key={sub.id} subscription={sub} />
      ))}
    </div>
  )
}
