// packages/react/src/components/WalletWidget.tsx
import React, { useEffect, useRef, useState } from 'react'
import { flushSync } from 'react-dom'
import {
  launchCheckout, createBalancePoller, formatCurrency,
  type PortalWallet, type BalancePoller,
} from '@monigo/portal-core'
import { useMonigoContext } from '../provider/context'

export interface WalletWidgetProps {
  walletId: string
  currency: string
  presets?: number[]
  pollIntervalMs?: number
  onFunded?: (reference: string) => void
  onError?: (err: unknown) => void
  className?: string
}

type View = 'loading' | 'ready' | 'error' | 'funding' | 'confirming'

export function WalletWidget({
  walletId, currency, presets = [1000, 5000, 10000],
  pollIntervalMs = 8000, onFunded, onError, className = '',
}: WalletWidgetProps): React.ReactElement {
  const { client, messages, locale } = useMonigoContext()
  const [view, setView] = useState<View>('loading')
  const [balance, setBalance] = useState('0')
  const [status, setStatus] = useState<PortalWallet['status']>('active')
  const [amount, setAmount] = useState('')
  const [open, setOpen] = useState(false)
  const [showStripe, setShowStripe] = useState(false)
  const stripeMount = useRef<HTMLDivElement>(null)
  const pollerRef = useRef<BalancePoller | undefined>(undefined)
  const abortRef = useRef<AbortController | undefined>(undefined)

  useEffect(() => {
    let cancelled = false
    const poller = createBalancePoller(client, walletId, {
      intervalMs: pollIntervalMs,
      onBalance: (b, w) => {
        if (cancelled) return
        setBalance(b); setStatus(w.status)
        setView((v) => (v === 'loading' ? 'ready' : v))
      },
      onError: (err) => {
        if (cancelled) return
        setView((v) => (v === 'loading' ? 'error' : v)); onError?.(err)
      },
    })
    pollerRef.current = poller
    poller.start()
    return () => { cancelled = true; poller.stop(); abortRef.current?.abort() }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [client, walletId, pollIntervalMs])

  const fund = async () => {
    const amt = parseFloat(amount)
    if (!amt || amt <= 0) return
    setView('funding')
    const controller = new AbortController()
    abortRef.current = controller
    try {
      const session = await client.initWalletFunding(walletId, { amount, currency })
      if (session.provider === 'stripe') {
        // Flush the mount <div> into the DOM so its ref attaches before launch.
        flushSync(() => setShowStripe(true))
      }
      const result = await launchCheckout(session, {
        ...(stripeMount.current ? { mountEl: stripeMount.current } : {}),
        signal: controller.signal,
      })
      setShowStripe(false)
      if (result.status === 'success') {
        setView('confirming')
        try { await pollerRef.current?.refreshNow() } catch { /* surfaced via onError */ }
        setView('ready'); setOpen(false); setAmount('')
        onFunded?.(result.reference)
      } else {
        setView('ready')
      }
    } catch (err) {
      setShowStripe(false)
      try {
        const redirect = await client.fundWallet(walletId, { amount, currency })
        if (typeof window !== 'undefined') { window.location.href = redirect.authorization_url; return }
      } catch { /* ignore */ }
      setView('ready'); onError?.(err)
    }
  }

  const cancelFunding = () => {
    abortRef.current?.abort()
    setShowStripe(false); setOpen(false); setAmount('')
    setView((v) => (v === 'funding' || v === 'confirming' ? 'ready' : v))
  }

  const card: React.CSSProperties = {
    padding: 'var(--monigo-space-5)', border: '1px solid var(--monigo-color-border)',
    borderRadius: 'var(--monigo-radius-lg)', display: 'flex', flexDirection: 'column', gap: 'var(--monigo-space-3)',
  }
  const primaryBtn: React.CSSProperties = {
    padding: 'var(--monigo-space-2) var(--monigo-space-4)', background: 'var(--monigo-color-primary)',
    color: 'var(--monigo-color-primary-fg)', border: 'none', borderRadius: 'var(--monigo-radius-md)',
    fontSize: 'var(--monigo-text-sm)', cursor: 'pointer',
  }

  return (
    <section className={`monigo-wallet-widget ${className}`} style={card}>
      <div style={{ display: 'flex', justifyContent: 'space-between' }}>
        <span style={{ fontWeight: 600 }}>{currency} balance</span>
        <span style={{ fontSize: 'var(--monigo-text-xs)', color: 'var(--monigo-color-muted-fg)', textTransform: 'uppercase' }}>{status}</span>
      </div>

      {view === 'loading' ? (
        <p style={{ margin: 0, color: 'var(--monigo-color-muted-fg)' }}>…</p>
      ) : view === 'error' ? (
        <p style={{ margin: 0, color: 'var(--monigo-color-danger)' }}>Unable to load balance</p>
      ) : (
        <p className="font-numeric" style={{ fontSize: 'var(--monigo-text-2xl)', fontWeight: 700, margin: 0 }}>
          {formatCurrency(balance, currency, locale)}
        </p>
      )}

      {!open ? (
        <button type="button" style={primaryBtn} onClick={() => setOpen(true)} disabled={view === 'loading'}>
          {messages['wallets.action.fund']}
        </button>
      ) : (
        <form onSubmit={(e) => { e.preventDefault(); void fund() }} style={{ display: 'flex', flexDirection: 'column', gap: 'var(--monigo-space-2)' }}>
          <div style={{ display: 'flex', gap: 'var(--monigo-space-2)', flexWrap: 'wrap' }}>
            {presets.map((p) => (
              <button key={p} type="button" onClick={() => setAmount(String(p))} disabled={view === 'funding'}
                style={{ padding: 'var(--monigo-space-1) var(--monigo-space-3)', border: '1px solid var(--monigo-color-border)', borderRadius: 'var(--monigo-radius-md)', background: 'var(--monigo-color-muted)', cursor: 'pointer', fontSize: 'var(--monigo-text-sm)' }}>
                {formatCurrency(String(p), currency, locale)}
              </button>
            ))}
          </div>
          <input type="number" step="0.01" min="0" required value={amount} aria-label="Amount"
            onChange={(e) => setAmount(e.target.value)} placeholder={`Amount (${currency})`} disabled={view === 'funding'}
            style={{ padding: 'var(--monigo-space-2)', border: '1px solid var(--monigo-color-border)', borderRadius: 'var(--monigo-radius-sm)', fontSize: 'var(--monigo-text-sm)' }} />
          <div style={{ display: 'flex', gap: 'var(--monigo-space-2)' }}>
            <button type="submit" style={primaryBtn} disabled={view === 'funding' || !amount}>
              {view === 'funding' ? messages['common.loading'] : messages['common.confirm']}
            </button>
            <button type="button" onClick={cancelFunding} disabled={view === 'confirming'}
              style={{ padding: 'var(--monigo-space-2) var(--monigo-space-3)', background: 'transparent', color: 'var(--monigo-color-muted-fg)', border: '1px solid var(--monigo-color-border)', borderRadius: 'var(--monigo-radius-md)', cursor: 'pointer' }}>
              {messages['common.cancel']}
            </button>
          </div>
        </form>
      )}

      {view === 'confirming' && <p style={{ margin: 0, color: 'var(--monigo-color-muted-fg)', fontSize: 'var(--monigo-text-sm)' }}>Confirming payment…</p>}
      {showStripe && <div ref={stripeMount} style={{ marginTop: 'var(--monigo-space-3)' }} />}
    </section>
  )
}

// packages/vue/src/components/WalletWidget.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, nextTick, watch } from 'vue'
import {
  launchCheckout, createBalancePoller, formatCurrency,
  type PortalWallet, type BalancePoller,
} from '@monigo/portal-core'
import { useMonigoContext } from '../provider/context'

interface Props {
  walletId: string
  currency: string
  presets?: number[]
  pollIntervalMs?: number
  class?: string
}
const props = withDefaults(defineProps<Props>(), { presets: () => [1000, 5000, 10000], pollIntervalMs: 8000, class: '' })
const emit = defineEmits<{ funded: [reference: string]; error: [err: unknown] }>()

const { client, messages, locale } = useMonigoContext()

type View = 'loading' | 'ready' | 'error' | 'funding' | 'confirming'
const view = ref<View>('loading')
const balance = ref('0')
const status = ref<PortalWallet['status']>('active')
const amount = ref('')
const open = ref(false)
const showStripe = ref(false)
const stripeMount = ref<HTMLDivElement | null>(null)
let poller: BalancePoller | undefined
let abortController: AbortController | undefined

function startPoller() {
  poller?.stop()
  poller = createBalancePoller(client, props.walletId, {
    intervalMs: props.pollIntervalMs,
    onBalance: (b, w) => { balance.value = b; status.value = (w as PortalWallet).status; if (view.value === 'loading') view.value = 'ready' },
    onError: (err) => { if (view.value === 'loading') view.value = 'error'; emit('error', err) },
  })
  poller.start()
}

onMounted(startPoller)
// Re-subscribe if the wallet or interval changes (parity with the React/Svelte widgets).
watch(() => [props.walletId, props.pollIntervalMs], startPoller)
onUnmounted(() => { poller?.stop(); abortController?.abort() })

async function fund() {
  const amt = parseFloat(amount.value)
  if (!amt || amt <= 0) return
  view.value = 'funding'
  const controller = new AbortController()
  abortController = controller
  try {
    const session = await client.initWalletFunding(props.walletId, { amount: String(amount.value), currency: props.currency })
    if (session.provider === 'stripe') {
      showStripe.value = true
      await nextTick() // flush so the stripeMount ref is attached before launch
    }
    const result = await launchCheckout(session, {
      ...(stripeMount.value ? { mountEl: stripeMount.value } : {}),
      signal: controller.signal,
    })
    showStripe.value = false
    if (result.status === 'success') {
      view.value = 'confirming'
      try { await poller?.refreshNow() } catch { /* surfaced via onError */ }
      view.value = 'ready'; open.value = false; amount.value = ''
      emit('funded', result.reference)
    } else {
      view.value = 'ready'
    }
  } catch (err) {
    showStripe.value = false
    try {
      const redirect = await client.fundWallet(props.walletId, { amount: String(amount.value), currency: props.currency })
      if (typeof window !== 'undefined') { window.location.href = redirect.authorization_url; return }
    } catch { /* ignore */ }
    view.value = 'ready'; emit('error', err)
  }
}

function cancelFunding() {
  abortController?.abort()
  showStripe.value = false; open.value = false; amount.value = ''
  if (view.value === 'funding' || view.value === 'confirming') view.value = 'ready'
}
</script>

<template>
  <section :class="['monigo-wallet-widget', props.class]" :style="{ padding: 'var(--monigo-space-5)', border: '1px solid var(--monigo-color-border)', borderRadius: 'var(--monigo-radius-lg)', display: 'flex', flexDirection: 'column', gap: 'var(--monigo-space-3)' }">
    <div :style="{ display: 'flex', justifyContent: 'space-between' }">
      <span :style="{ fontWeight: '600' }">{{ props.currency }} balance</span>
      <span :style="{ fontSize: 'var(--monigo-text-xs)', color: 'var(--monigo-color-muted-fg)', textTransform: 'uppercase' }">{{ status }}</span>
    </div>

    <p v-if="view === 'loading'" :style="{ margin: '0', color: 'var(--monigo-color-muted-fg)' }">…</p>
    <p v-else-if="view === 'error'" :style="{ margin: '0', color: 'var(--monigo-color-danger)' }">Unable to load balance</p>
    <p v-else class="font-numeric" :style="{ fontSize: 'var(--monigo-text-2xl)', fontWeight: '700', margin: '0' }">
      {{ formatCurrency(balance, props.currency, locale) }}
    </p>

    <button v-if="!open" type="button" class="primary"
      :style="{ padding: 'var(--monigo-space-2) var(--monigo-space-4)', background: 'var(--monigo-color-primary)', color: 'var(--monigo-color-primary-fg)', border: 'none', borderRadius: 'var(--monigo-radius-md)', fontSize: 'var(--monigo-text-sm)', cursor: 'pointer' }"
      :disabled="view === 'loading'" @click="open = true">
      {{ messages['wallets.action.fund'] }}
    </button>

    <form v-else @submit.prevent="fund" :style="{ display: 'flex', flexDirection: 'column', gap: 'var(--monigo-space-2)' }">
      <div :style="{ display: 'flex', gap: 'var(--monigo-space-2)', flexWrap: 'wrap' }">
        <button v-for="p in props.presets" :key="p" type="button" :disabled="view === 'funding'" @click="amount = String(p)"
          :style="{ padding: 'var(--monigo-space-1) var(--monigo-space-3)', border: '1px solid var(--monigo-color-border)', borderRadius: 'var(--monigo-radius-md)', background: 'var(--monigo-color-muted)', cursor: 'pointer', fontSize: 'var(--monigo-text-sm)' }">
          {{ formatCurrency(String(p), props.currency, locale) }}
        </button>
      </div>
      <input v-model="amount" type="number" step="0.01" min="0" required aria-label="Amount" :placeholder="`Amount (${props.currency})`" :disabled="view === 'funding'"
        :style="{ padding: 'var(--monigo-space-2)', border: '1px solid var(--monigo-color-border)', borderRadius: 'var(--monigo-radius-sm)', fontSize: 'var(--monigo-text-sm)' }" />
      <div :style="{ display: 'flex', gap: 'var(--monigo-space-2)' }">
        <button type="submit" class="primary" :disabled="view === 'funding' || !amount"
          :style="{ padding: 'var(--monigo-space-2) var(--monigo-space-4)', background: 'var(--monigo-color-primary)', color: 'var(--monigo-color-primary-fg)', border: 'none', borderRadius: 'var(--monigo-radius-md)', fontSize: 'var(--monigo-text-sm)', cursor: 'pointer' }">
          {{ view === 'funding' ? messages['common.loading'] : messages['common.confirm'] }}
        </button>
        <button type="button" :disabled="view === 'confirming'" @click="cancelFunding"
          :style="{ padding: 'var(--monigo-space-2) var(--monigo-space-3)', background: 'transparent', color: 'var(--monigo-color-muted-fg)', border: '1px solid var(--monigo-color-border)', borderRadius: 'var(--monigo-radius-md)', cursor: 'pointer' }">
          {{ messages['common.cancel'] }}
        </button>
      </div>
    </form>

    <p v-if="view === 'confirming'" :style="{ margin: '0', color: 'var(--monigo-color-muted-fg)', fontSize: 'var(--monigo-text-sm)' }">Confirming payment…</p>
    <div v-if="showStripe" ref="stripeMount" :style="{ marginTop: 'var(--monigo-space-3)' }"></div>
  </section>
</template>
