// packages/react/src/components/WalletList.tsx
import React, { useEffect } from 'react'
import { type PortalWallet } from '@monigo/portal-core'
import { useMonigoContext } from '../provider/context'
import { useWallets } from '../hooks/useWallets'
import { WalletCard } from './WalletCard'
import { Skeleton } from './shared/Skeleton'
import { EmptyState } from './shared/EmptyState'
import { ErrorState } from './shared/ErrorState'

export interface WalletListProps {
  onWalletClick?: (wallet: PortalWallet) => void
  className?: string
}

export function WalletList({ onWalletClick, className = '' }: WalletListProps): React.ReactElement {
  const { client, messages } = useMonigoContext()
  const { state, dispatch } = useWallets(client)

  useEffect(() => { dispatch({ type: 'load' }) }, [dispatch])

  if (state.status === 'idle' || state.status === 'loading') return <Skeleton rows={3} />
  if (state.status === 'error') {
    return <ErrorState error={state.error} onRetry={() => dispatch({ type: 'refresh' })} retryLabel={messages['common.retry']} />
  }
  if (state.wallets.length === 0) return <EmptyState message={messages['wallets.empty']} />

  return (
    <div className={`monigo-wallet-list ${className}`} style={{ display: 'flex', flexDirection: 'column', gap: 'var(--monigo-space-3)' }}>
      {state.wallets.map((wallet) => (
        <WalletCard key={wallet.id} wallet={wallet} {...(onWalletClick !== undefined && { onClick: onWalletClick })} />
      ))}
    </div>
  )
}

// packages/vue/src/components/WalletList.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue'
import type { PortalWallet } from '@monigo/portal-core'
import { useMonigoContext } from '../provider/context'
import { useWallets } from '../stores/useWallets'
import WalletCard from './WalletCard.vue'
import Skeleton from './shared/Skeleton.vue'
import EmptyState from './shared/EmptyState.vue'
import ErrorState from './shared/ErrorState.vue'

interface Props { class?: string }
const props = withDefaults(defineProps<Props>(), { class: '' })
const emit = defineEmits<{ walletClick: [wallet: PortalWallet] }>()

const { client, messages } = useMonigoContext()
const { state, dispatch, dispose } = useWallets(client)

onMounted(() => dispatch({ type: 'load' }))
onUnmounted(dispose)
</script>

<template>
  <div :class="['monigo-wallet-list', props.class]">
    <Skeleton v-if="state.status === 'idle' || state.status === 'loading'" :rows="3" />
    <ErrorState
      v-else-if="state.status === 'error'"
      :error="state.error"
      :on-retry="() => dispatch({ type: 'refresh' })"
      :retry-label="messages['common.retry']"
    />
    <EmptyState v-else-if="state.wallets.length === 0" :message="messages['wallets.empty']" />
    <div
      v-else
      :style="{ display: 'flex', flexDirection: 'column', gap: 'var(--monigo-space-3)' }"
    >
      <WalletCard
        v-for="wallet in state.wallets"
        :key="wallet.id"
        :wallet="wallet"
        @wallet-click="(w) => emit('walletClick', w)"
      />
    </div>
  </div>
</template>
