// packages/vue/src/components/shared/EmptyState.vue
<script setup lang="ts">
interface Props {
  message: string
  class?: string
}
const props = defineProps<Props>()
</script>

<template>
  <p
    :class="['monigo-empty', props.class]"
    :style="{
      padding: 'var(--monigo-space-6)',
      textAlign: 'center',
      color: 'var(--monigo-color-muted-fg)',
      fontSize: 'var(--monigo-text-sm)',
    }"
  >
    {{ props.message }}
  </p>
</template>

// packages/react/src/components/shared/EmptyState.tsx
import React from 'react'

export interface EmptyStateProps {
  message: string
  className?: string
}

export function EmptyState({ message, className = '' }: EmptyStateProps): React.ReactElement {
  return (
    <p
      className={`monigo-empty ${className}`}
      style={{
        padding: 'var(--monigo-space-6)',
        textAlign: 'center',
        color: 'var(--monigo-color-muted-fg)',
        fontSize: 'var(--monigo-text-sm)',
      }}
    >
      {message}
    </p>
  )
}
