// packages/vue/src/components/shared/ErrorState.vue
<script setup lang="ts">
interface Props {
  error: Error
  onRetry?: () => void
  retryLabel?: string
  class?: string
}
const props = withDefaults(defineProps<Props>(), { retryLabel: 'Try again', class: '' })
</script>

<template>
  <div
    :class="['monigo-error', props.class]"
    role="alert"
    :style="{ padding: 'var(--monigo-space-6)', textAlign: 'center' }"
  >
    <p :style="{ color: 'var(--monigo-color-danger)', marginBottom: 'var(--monigo-space-3)' }">
      {{ props.error.message }}
    </p>
    <button
      v-if="props.onRetry"
      type="button"
      @click="props.onRetry()"
      :style="{
        padding: 'var(--monigo-space-2) var(--monigo-space-4)',
        background: 'var(--monigo-color-primary)',
        color: 'var(--monigo-color-primary-fg)',
        border: 'none',
        borderRadius: 'var(--monigo-radius-md)',
        cursor: 'pointer',
      }"
    >
      {{ props.retryLabel }}
    </button>
  </div>
</template>

// packages/react/src/components/shared/ErrorState.tsx
import React from 'react'

export interface ErrorStateProps {
  error: Error
  onRetry?: () => void
  retryLabel?: string
  className?: string
}

export function ErrorState({
  error,
  onRetry,
  retryLabel = 'Try again',
  className = '',
}: ErrorStateProps): React.ReactElement {
  return (
    <div
      className={`monigo-error ${className}`}
      role="alert"
      style={{ padding: 'var(--monigo-space-6)', textAlign: 'center' }}
    >
      <p style={{ color: 'var(--monigo-color-danger)', marginBottom: 'var(--monigo-space-3)' }}>
        {error.message}
      </p>
      {onRetry && (
        <button
          type="button"
          onClick={onRetry}
          style={{
            padding: 'var(--monigo-space-2) var(--monigo-space-4)',
            background: 'var(--monigo-color-primary)',
            color: 'var(--monigo-color-primary-fg)',
            border: 'none',
            borderRadius: 'var(--monigo-radius-md)',
            cursor: 'pointer',
          }}
        >
          {retryLabel}
        </button>
      )}
    </div>
  )
}
